---
title: "Day 3 - Conditionals & Loops"
author: "Erika"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
```

#### `if` statements

```{r}
burrito <- 4

if (burrito > 2) {
  print("I love burritos!")
}
```

```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "x") #r

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```

#### `if-else` statement

```{r}
pika <- 50

if (pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}
```


#### Example of in operator
```{r}
tatooine_characters <- starwars %>% 
  filter(homeworld == "Tatooine")

# Use %in% operator to check for multiple positive matches
tatooine_endor_naboo <- starwars %>% 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))

# In words: Does the value in the homeworld variable for that row exist IN that vector?
```

